# shardkv-demo 集群启动配置

# --- Raft State 大小阈值（字节），超过此值时触发快照 ---
# 0 或负值表示禁用快照。默认 100 KB。
# 注意：阈值过小会造成高并发读写时频繁触发快照。由于快照在写锁内进行，gob序列化耗时，频繁快照可能会阻塞方法调用，使服务暂时不可用。
maxRaftState: 100000

# --- 每组默认节点数 ---
nsrv: 3

# --- 是否以可靠网络启动 (可在运行中动态修改) ---
reliable: true

# --- 客户端池容量（同时限制 CAS 并发竞赛 & 批量写入并发度）---
# 默认 500
clerkPoolSize: 500

# --- 初始启动的 Shard Group 列表，指定组号及副本节点数 ---
# 说明：
# - gid:     组 ID，正整数（1, 2, 3 ...）
# - servers: 该组节点数（可选，省略则使用 nsrv）

# 示例：创建一个初始有 3 个组（1, 2, 5），每组分别有5, 7, 3 个节点的分片集群
#groups:
#  - gid: 1
#    servers: 5
#  - gid: 2
#    servers: 7
#  - gid: 5
#    servers: 3  (此行可省略，若 nsrv = 3)

# 当前配置：1 组，3 节点
groups:
  - gid: 1
    servers: 3